TASK: Properly import mousetrap-global-bind
to mitigate TS-Error:
Resources/Private/JavaScript/bootstrap/createKeyBindings.ts:18:15 -
error TS2339: Property 'bindGlobal' does not exist on type
'MousetrapStatic'.